# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NTQ0RPzfxm9HuZomW7YGVi6O_pBAsb_v
"""

import matplotlib.pyplot as plt
import numpy as np
# make data
x=np.linspace(0,10,100)
print(x)
y=4+2*np.sin(2*x)
print(y)
fig, ax=plt.subplots()
ax.plot(x,y,linewidth=2.0)
plt.show()
import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6,78,45,12,35,7,66,12,45,36,74,56])
y=np.array([0,2,61,36,45,13,44,78,5,41,15,75,30])
plt.scatter(x,y,color='red')
plt.show()